[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# --- Prod : force l’URL https du site ---
[context.production]
  command = "hugo -b https://hugo.hackethical.be/"

# --- Deploy Previews : utilise l’URL propre au preview ---
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

# --- Branch deploys (optionnel, pratique en test) ---
[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"
